package db

const EDIT_STATUS_NOT_DONE = 0
const EDIT_STATUS_PARTIAL = 1
const EDIT_STATUS_DONE = 2

const EDIT_CLASSIFICATION_VANDALISM = 0
const EDIT_CLASSIFICATION_CONSTRUCTIVE = 1
const EDIT_CLASSIFICATION_SKIPPED = 2
const EDIT_CLASSIFICATION_UNKNOWN = 3
