INSERT INTO `edit_group` VALUES
    (1, "Legacy Report Interface Import", 0),
    (2, "Report Interface Import", 45),
    (3, "r81 False Negatives", 20),
    (4, "Random Edits", 40),
    (5, "False Negatives 2", 15),
    (6, "False Positives 2", 25),
    (7, "Original Training Set - C - Train", 0),
    (8, "Original Training Set - C - Trail", 0),
    (9, "Original Training Set - D - Train", 0),
    (10, "Original Training Set - D - Trail", 0),
    (11, "Original Training Set - D - Bays Train", 0),
    (12, "Original Training Set - D - All", 0),
    (13, "Original Testing Training Set - C - Train", 0),
    (14, "Original Testing Training Set - C - Trail", 0),
    (15, "Original Testing Training Set - D - Train", 0),
    (16, "Original Testing Training Set - D - Trail", 0),
    (17, "Original Testing Training Set - D - Bays Train", 0),
    (18, "Original Testing Training Set - D - All", 0),
    (19, "Original Testing Training Set - Auto - Train", 0),
    (20, "Original Testing Training Set - Auto - Trail", 0),
    (21, "Original Testing Training Set - Old Triplet - Train", 0),
    (22, "Original Testing Training Set - Old Triplet - Trail", 0),
    (23, "Original Testing Training Set - Old Triplet - Bays Train", 0),
    (24, "Original Testing Training Set - Old Triplet - All", 0),
    (25, "Original Testing Training Set - Random Edits 50/50 - Train", 0),
    (26, "Original Testing Training Set - Random Edits 50/50 - Trail", 0),
    (27, "Original Testing Training Set - Random Edits 50/50 - All", 0),
    (28, "Original Testing Training Set - Very Large - Train", 0),
    (29, "Original Testing Training Set - Very Large - Trail", 0),
    (30, "Original Testing Training Set - Very Large - Bays Train", 0),
    (31, "Original Testing Training Set - Very Large - All", 0);
